# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{YoutubeTools}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Maykon Luis Capellari"]
  s.date = %q{2010-09-27}
  s.description = %q{Gem from search, download and converter youtube videos to mp3}
  s.email = %q{maykon_capellari@yahoo.com.br}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO.rdoc",
     "VERSION",
     "init.rb",
     "lib/youtube_tools.rb",
     "lib/youtube_tools/converter.rb",
     "lib/youtube_tools/downloader.rb",
     "lib/youtube_tools/searcher.rb",
     "test/helper.rb",
     "test/test_YoutubeTools.rb"
  ]
  s.homepage = %q{http://github.com/maykon/YoutubeTools}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Gem from search, download and converter youtube videos to mp3}
  s.test_files = [
    "test/test_YoutubeTools.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, [">= 0"])
    else
      s.add_dependency(%q<minitest>, [">= 0"])
    end
  else
    s.add_dependency(%q<minitest>, [">= 0"])
  end
end

